CREATE SCHEMA IF NOT EXISTS core;

CREATE TABLE IF NOT EXISTS core.teams (
    team_id SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    official_name VARCHAR(63) UNIQUE NOT NULL,
    is_international BOOLEAN NOT NULL,
    franchise VARCHAR(15),
    status TEXT NOT NULL DEFAULT 'ACTIVE'
    CHECK (status IN ('ACTIVE', 'DISCONTINUED', 'BANNED'))
);